### ISSUE TITLE
GLTF Model position data should reside in a separate vertex buffer.

### ISSUE THREAD

**Issue by razvan1024** [DiligentGraphics/DiligentTools#15]
The GLTFRenderer is a forward renderer without a depth prepass. This leads to possible overdraw when the multiple models are drawn. 
In order to add a depth prepass, 2 additional shaders are needed. The vertex shader of the depth prepass only the vertex position and does not care about any other data(like normals or texture coordinates). 
The current implementation of the GLTFModel provides a vertex buffer where position is combined with other data. Using this buffer for the depth prepass vertex shader would be possible, but inefficient.

**Comment by razvan1024** [comment]
Pull request #16 and https://github.com/DiligentGraphics/DiligentFX/pull/5 solve this issue.

**Comment by TheMostDiligent** [comment]
Hi! Thanks for submitting the PRs, I believe it does make sense. One concern though is that for alpha-cut materials you will still have to provide the second buffer too, because the shader [clips pixels](https://github.com/DiligentGraphics/DiligentFX/blob/master/Shaders/GLTF_PBR/private/RenderGLTF_PBR.psh#L87) based on the transparency value. For opaque models though this is not required.

**Comment by razvan1024** [comment]
Hi, you are right, I did not look into the pixel shader. 

I moved back UV0 and UV1 to the first vertex buffer, so now alpha masked  materials should work as well.

**Comment by TheMostDiligent** [comment]
I added comment to your change. I think that original version will work better. Alpha-cut material may be handled separately from opaque materials, which will only need position

**Comment by razvan1024** [comment]
Ok, you can reject the pull requests.
