### ISSUE TITLE
Further simplify package manager handling

### ISSUE THREAD

**Issue by AndreyMlashkin** [DiligentGraphics/DiligentTools#177]
(Click "Preview" to turn any URL into a clickable link)

I have just finished developing diligent-tools conan package and I have several proposals to simplify adding further versions:

- [X] Make possible to set/override DILIGENT_CORE_DIR.
https://github.com/conan-io/conan-center-index/blob/c5a7739723dad6364bacf122874ed534b51d1a7a/recipes/diligent-tools/all/patches/0010-fix-render-state-notation-paths.diff
- [X] Make it possible to switch off clang code validation with a some cmake variable
- [X] Don't include imgui sources directly. Just link additional sources to already existing imgui lib
https://github.com/conan-io/conan-center-index/blob/f348876afd72c8b380375c8f0916eede87044763/recipes/diligent-tools/all/patches/0006-2.5.2-use-imgui-from-conan.diff

And thank you for working in this direction, it was much easier to implement v2.5.2.

**Comment by TheMostDiligent** [comment]
> 1. Make possible to set/override DILIGENT_CORE_DIR.

Will it work for you if the source directory is detected automatically, e.g.:

```CMake
get_target_property(GRAPHICS_ENGINE_SOURCE_DIR Diligent-GraphicsEngine SOURCE_DIR)

set(REFLECTED
    ${GRAPHICS_ENGINE_SOURCE_DIR}/interface/BlendState.h
    ${GRAPHICS_ENGINE_SOURCE_DIR}/interface/DepthStencilState.h
   ...
)
```

> 2. Make it possible to switch off clang code validation with a some cmake variable

Do you mean [this](https://github.com/DiligentGraphics/DiligentTools/blob/master/RenderStateNotation/CMakeLists.txt#L67)? 
`DILIGENT_NO_FORMAT_VALIDATION` disables format validation for all modules.

**Comment by AndreyMlashkin** [comment]
In conan we handle one repository as a separate packet without submodules.
On this reason there is no diligent-engine packet...
Conan would need DILIGENT_CORE_SOURCE_DIR

**Comment by AndreyMlashkin** [comment]
This line does not respect the flag DILIGENT_NO_FORMAT_VALIDATION.

https://github.com/conan-io/conan-center-index/blob/c5a7739723dad6364bacf122874ed534b51d1a7a/recipes/diligent-tools/all/patches/0010-fix-render-state-notation-paths.diff#L40

**Comment by TheMostDiligent** [comment]
For the patches:

- [ ] [0006](https://github.com/conan-io/conan-center-index/blob/c5a7739723dad6364bacf122874ed534b51d1a7a/recipes/diligent-tools/all/patches/0006-2.5.2-use-imgui-from-conan.diff)
- [X] [0007](https://github.com/conan-io/conan-center-index/blob/c5a7739723dad6364bacf122874ed534b51d1a7a/recipes/diligent-tools/all/patches/0007-2.5.2-use-diligent-core-dependencies.diff) can be fixed by aliasing all Diligent targets as `diligent-core::diligent-core` in master CMake, e.g.:
```
add_library(Diligent-BuildSettings ALIAS diligent-core::diligent-core)
```
- [X] [0008](https://github.com/conan-io/conan-center-index/blob/c5a7739723dad6364bacf122874ed534b51d1a7a/recipes/diligent-tools/all/patches/0008-2.5.2-use-conan-dependencies.diff) - same as 0007
- [ ] [0009](https://github.com/conan-io/conan-center-index/blob/c5a7739723dad6364bacf122874ed534b51d1a7a/recipes/diligent-tools/all/patches/0009-2.5.2-fix-include-path.diff)
- [X] [0010](https://github.com/conan-io/conan-center-index/blob/c5a7739723dad6364bacf122874ed534b51d1a7a/recipes/diligent-tools/all/patches/0010-fix-render-state-notation-paths.diff) - should be fixed by https://github.com/DiligentGraphics/DiligentTools/commit/e604522a83d2186f9df823515751c8034b7fb7e8 and https://github.com/DiligentGraphics/DiligentTools/commit/b7dd9691cfd15ede14225aac7cba3db02843e7d9
- [X] [0011](https://github.com/conan-io/conan-center-index/blob/c5a7739723dad6364bacf122874ed534b51d1a7a/recipes/diligent-tools/all/patches/0011-2.5.2-use-conan-dependencies-part2.diff) - same as 0008 and 0007

**Comment by AndreyMlashkin** [comment]
This PR closes all items except for imgui:
https://github.com/conan-io/conan-center-index/pull/11819#issuecomment-1190000453

**Comment by TheMostDiligent** [comment]
All done
